name: build-resume

on:
  push:
    branches: [master]
    paths:
      - "markdown/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build resume
        run: docker compose up

      - name: Make index
        run: cd output && sudo cp resume.html index.html

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: |
            output/resume.pdf

      - name: Publish HTML
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
